### ISSUE TITLE
Sicherheitsrestriktion beim Zugriff auf Google Spreadsheet

### ISSUE THREAD

**Issue by studermartin** [fhgr2/fusionscheck-kurzvariante#38]
Aktuell erscheint folgender Fehler:
`Failed to load https://docs.google.com/forms/d/1piWA6Wtn4fV2PN8LWfP4-HkhXu6sXoKBKAa-Fiokwrg/formResponse: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://preview.htw01.snowflakehosting.ch' is therefore not allowed access.`

**Comment by MartinStuderHTWChur** [comment]
Mail von snowflake.ch.

[[snowflake #4248.54] Neuer Kommentar_ Code Analyse Google Forms auf Foschung und Dienstleistung.pdf](https://github.com/htwchur/fusionscheck-kurzvariante/files/2492407/snowflake.4248.54.Neuer.Kommentar_.Code.Analyse.Google.Forms.auf.Foschung.und.Dienstleistung.pdf)

**Comment by MartinStuderHTWChur** [comment]
See https://jira.htwchur.ch/browse/PROR-250

Will not be fixed.
